// <auto-generated />
using System;
using FinalHerramientas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace finalHerramientas.Migrations
{
    [DbContext(typeof(LugarContext))]
    partial class LugarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("finalHerramientas.Models.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dias")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIda")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoRuta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pais")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lugar");
                });
#pragma warning restore 612, 618
        }
    }
}
